pages:
  - 主页: 'index.md'
  - 意见反馈区使用教程: 'issues.md'
  - ItemRender使用教程: 'itemrender.md'
  - 模组添加/修改教程: 'mod.md'

site_name: MCMOD百科官方文档

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

theme: readthedocs

extra_css:
  - css/code.css
