pages:
  - 主页: 'index.md'
  - 资料编写指南: 'styleguide.md'
  - 用户组: 'user.md'
  - 维护小组: 'group.md'
  - 意见反馈区使用教程: 'issues.md'
  - ItemRender使用教程: 'itemrender.md'
  - 模组添加/编辑教程: 'mod.md'
  - 资料添加/编辑教程: 'data.md'
  - 合成表添加/编辑教程: 'recipe.md'
  - 日志添加/编辑教程: 'log.md'
  - 编辑器使用教程与准则: 'editor.md'

site_name: MCMOD百科官方文档

markdown_extensions:
  - admonition
  - smarty
  - sane_lists

theme: readthedocs

extra_css:
  - css/code.css
